INSERT INTO `dropdown_options` (`type`, `value`, `order`) VALUES
  ('backup_required', 'If Possible', 1),
  ('backup_required', 'No', 2),
  ('backup_required', 'Yes', 3),
  ('branch', 'ALAPPUZHA', 1),
  ('branch', 'CALICUT', 2),
  ('branch', 'CHENGANNUR', 3),
  ('branch', 'DREAMS MALL KOTTIYAM', 4),
  ('branch', 'FORUM MALL COCHIN', 5),
  ('branch', 'KADAVANTHRA', 6),
  ('branch', 'KANHANGAD', 7),
  ('branch', 'KANNUR', 8),
  ('branch', 'KOLLAM', 9),
  ('branch', 'KOTTAKKAL', 10),
  ('branch', 'KOTTAYAM', 11),
  ('branch', 'LULU COCHIN', 12),
  ('branch', 'LULU TVM', 13),
  ('branch', 'MANJERI', 14),
  ('branch', 'MOT', 15),
  ('branch', 'NILAMBUR', 16),
  ('branch', 'OBERON', 17),
  ('branch', 'PALA', 18),
  ('branch', 'PATHANAMTHITTA', 19),
  ('branch', 'PERINTHALMANNA', 20),
  ('branch', 'PERUMBAVOOR', 21),
  ('branch', 'RAVIPURAM', 22),
  ('branch', 'SOBHA CITY', 23),
  ('branch', 'THALASSERY', 24),
  ('branch', 'THODUPUZHA', 25),
  ('branch', 'THRISSUR', 26),
  ('branch', 'TRIPUNITHURA', 27),
  ('branch', 'Y MALL', 28),
  ('branch', 'CHENNAI', 29),
  ('branch', 'COIMBATORE', 30),
  ('call_type', 'AMC Visit', 4),
  ('call_type', 'Carry In', 5),
  ('call_type', 'Installation', 6),
  ('call_type', 'Onsite Visit', 7),
  ('call_type', 'Pickup Request', 8),
  ('call_type', 'Remote Support', 9),
  ('complaint_type', 'Chip Level', 10),
  ('complaint_type', 'HW-SW', 11),
  ('complaint_type', 'Printer', 12),
  ('device_category', 'Accessories', 13),
  ('device_category', 'All-In-One PC', 14),
  ('device_category', 'Desktop', 15),
  ('device_category', 'Laptop', 16),
  ('device_category', 'Mobile', 17),
  ('device_category', 'Monitor', 18),
  ('device_category', 'Others', 19),
  ('device_category', 'Printer', 20),
  ('device_category', 'Toner', 21),
  ('priority', 'Low', 22),
  ('priority', 'Normal', 23),
  ('priority', 'High', 24),
  ('priority', 'Urgent', 25),
  ('warranty_status', 'Not Sure', 26),
  ('warranty_status', 'Out Of Warranty', 27),
  ('warranty_status', 'Under Warranty', 28);
